FROM image-registry.apps.silver.devops.gov.bc.ca/3cd915-tools/jenkins-slave-centos-net5

LABEL \
  io.k8s.display-name="Jenkins Agent .NET 5.0" \
  io.k8s.description="The jenkins agent dotnet image has the dotnet tools on top of the jenkins slave base image." \
  io.openshift.tags="openshift,jenkins,agent,dotnet,dotnet50"

ARG SONAR_VERSION=4.9.0
ARG COVERLET_VERSION=1.7.2
USER 0

# Install SonarQube Scanner
RUN dotnet tool install --global dotnet-sonarscanner --version ${SONAR_VERSION} && \
  dotnet tool install --global coverlet.console --version ${COVERLET_VERSION}

ENV PATH=$PATH:$HOME/.dotnet/tools

USER 1001
